with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
filename: "mock_{{ .InterfaceNameSnake }}.go"
mockname: "Mock{{.InterfaceName}}"
packages:
  boilerplates/payment/internal/service:
    interfaces:
      PaymentService:
  boilerplates/payment/internal/config:
    interfaces:
      LoggerConfig:
      PaymentGRPCConfig: