
with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
filename: "mock_{{ .InterfaceNameSnake }}.go"
mockname: "Mock{{.InterfaceName}}"
packages:
  boilerplates/inventory/internal/repository:
    interfaces:
      PartRepository:
  boilerplates/inventory/internal/service:
    interfaces:
      PartService:
  boilerplates/inventory/internal/config:
    interfaces:
      LoggerConfig:
      InventoryGRPCConfig:
      MongoConfig: