// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockMongoConfig is an autogenerated mock type for the MongoConfig type
type MockMongoConfig struct {
	mock.Mock
}

type MockMongoConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMongoConfig) EXPECT() *MockMongoConfig_Expecter {
	return &MockMongoConfig_Expecter{mock: &_m.Mock}
}

// DatabaseName provides a mock function with no fields
func (_m *MockMongoConfig) DatabaseName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DatabaseName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockMongoConfig_DatabaseName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DatabaseName'
type MockMongoConfig_DatabaseName_Call struct {
	*mock.Call
}

// DatabaseName is a helper method to define mock.On call
func (_e *MockMongoConfig_Expecter) DatabaseName() *MockMongoConfig_DatabaseName_Call {
	return &MockMongoConfig_DatabaseName_Call{Call: _e.mock.On("DatabaseName")}
}

func (_c *MockMongoConfig_DatabaseName_Call) Run(run func()) *MockMongoConfig_DatabaseName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMongoConfig_DatabaseName_Call) Return(_a0 string) *MockMongoConfig_DatabaseName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMongoConfig_DatabaseName_Call) RunAndReturn(run func() string) *MockMongoConfig_DatabaseName_Call {
	_c.Call.Return(run)
	return _c
}

// URI provides a mock function with no fields
func (_m *MockMongoConfig) URI() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for URI")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockMongoConfig_URI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'URI'
type MockMongoConfig_URI_Call struct {
	*mock.Call
}

// URI is a helper method to define mock.On call
func (_e *MockMongoConfig_Expecter) URI() *MockMongoConfig_URI_Call {
	return &MockMongoConfig_URI_Call{Call: _e.mock.On("URI")}
}

func (_c *MockMongoConfig_URI_Call) Run(run func()) *MockMongoConfig_URI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMongoConfig_URI_Call) Return(_a0 string) *MockMongoConfig_URI_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMongoConfig_URI_Call) RunAndReturn(run func() string) *MockMongoConfig_URI_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMongoConfig creates a new instance of MockMongoConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMongoConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMongoConfig {
	mock := &MockMongoConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
