// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockPostgresConfig is an autogenerated mock type for the PostgresConfig type
type MockPostgresConfig struct {
	mock.Mock
}

type MockPostgresConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostgresConfig) EXPECT() *MockPostgresConfig_Expecter {
	return &MockPostgresConfig_Expecter{mock: &_m.Mock}
}

// MigrationsDir provides a mock function with no fields
func (_m *MockPostgresConfig) MigrationsDir() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MigrationsDir")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPostgresConfig_MigrationsDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MigrationsDir'
type MockPostgresConfig_MigrationsDir_Call struct {
	*mock.Call
}

// MigrationsDir is a helper method to define mock.On call
func (_e *MockPostgresConfig_Expecter) MigrationsDir() *MockPostgresConfig_MigrationsDir_Call {
	return &MockPostgresConfig_MigrationsDir_Call{Call: _e.mock.On("MigrationsDir")}
}

func (_c *MockPostgresConfig_MigrationsDir_Call) Run(run func()) *MockPostgresConfig_MigrationsDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPostgresConfig_MigrationsDir_Call) Return(_a0 string) *MockPostgresConfig_MigrationsDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPostgresConfig_MigrationsDir_Call) RunAndReturn(run func() string) *MockPostgresConfig_MigrationsDir_Call {
	_c.Call.Return(run)
	return _c
}

// URI provides a mock function with no fields
func (_m *MockPostgresConfig) URI() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for URI")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPostgresConfig_URI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'URI'
type MockPostgresConfig_URI_Call struct {
	*mock.Call
}

// URI is a helper method to define mock.On call
func (_e *MockPostgresConfig_Expecter) URI() *MockPostgresConfig_URI_Call {
	return &MockPostgresConfig_URI_Call{Call: _e.mock.On("URI")}
}

func (_c *MockPostgresConfig_URI_Call) Run(run func()) *MockPostgresConfig_URI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPostgresConfig_URI_Call) Return(_a0 string) *MockPostgresConfig_URI_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPostgresConfig_URI_Call) RunAndReturn(run func() string) *MockPostgresConfig_URI_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostgresConfig creates a new instance of MockPostgresConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostgresConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostgresConfig {
	mock := &MockPostgresConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
