// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderHTTPConfig is an autogenerated mock type for the OrderHTTPConfig type
type MockOrderHTTPConfig struct {
	mock.Mock
}

type MockOrderHTTPConfig_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderHTTPConfig) EXPECT() *MockOrderHTTPConfig_Expecter {
	return &MockOrderHTTPConfig_Expecter{mock: &_m.Mock}
}

// Address provides a mock function with no fields
func (_m *MockOrderHTTPConfig) Address() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockOrderHTTPConfig_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockOrderHTTPConfig_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *MockOrderHTTPConfig_Expecter) Address() *MockOrderHTTPConfig_Address_Call {
	return &MockOrderHTTPConfig_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *MockOrderHTTPConfig_Address_Call) Run(run func()) *MockOrderHTTPConfig_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderHTTPConfig_Address_Call) Return(_a0 string) *MockOrderHTTPConfig_Address_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderHTTPConfig_Address_Call) RunAndReturn(run func() string) *MockOrderHTTPConfig_Address_Call {
	_c.Call.Return(run)
	return _c
}

// ReadTimeout provides a mock function with no fields
func (_m *MockOrderHTTPConfig) ReadTimeout() time.Duration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadTimeout")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// MockOrderHTTPConfig_ReadTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadTimeout'
type MockOrderHTTPConfig_ReadTimeout_Call struct {
	*mock.Call
}

// ReadTimeout is a helper method to define mock.On call
func (_e *MockOrderHTTPConfig_Expecter) ReadTimeout() *MockOrderHTTPConfig_ReadTimeout_Call {
	return &MockOrderHTTPConfig_ReadTimeout_Call{Call: _e.mock.On("ReadTimeout")}
}

func (_c *MockOrderHTTPConfig_ReadTimeout_Call) Run(run func()) *MockOrderHTTPConfig_ReadTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderHTTPConfig_ReadTimeout_Call) Return(_a0 time.Duration) *MockOrderHTTPConfig_ReadTimeout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderHTTPConfig_ReadTimeout_Call) RunAndReturn(run func() time.Duration) *MockOrderHTTPConfig_ReadTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderHTTPConfig creates a new instance of MockOrderHTTPConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderHTTPConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderHTTPConfig {
	mock := &MockOrderHTTPConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
